# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base:3.19'
  amd64: 'ghcr.io/home-assistant/amd64-base:3.19'
  armhf: 'ghcr.io/home-assistant/armhf-base:3.19'
  armv7: 'ghcr.io/home-assistant/armv7-base:3.19'
  i386: 'ghcr.io/home-assistant/i386-base:3.19'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: Example add-on'
  org.opencontainers.image.description: 'Example add-on to use as a blueprint for new add-ons.'
  org.opencontainers.image.source: 'https://github.com/bfra-me/ha-addon-repository'
  org.opencontainers.image.licenses: 'Apache License 2.0'
