# Extend default settings for all of my @bfra-me repositories defined in .github/settings.yml
_extends: .github

repository:
  description: Template repository for a Home Assistant add-on repository
  topics: homeassistant, home-assistant, hassio, addon, addons, template

branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Deprecated: The list of status checks to require in order to merge into this branch. If any of these checks have recently been set by a particular GitHub App, they will be required to come from that app in future for the branch to merge. Use checks instead of contexts for more fine-grained control.
        contexts: []
        # The list of status checks to require in order to merge into this branch.
        # checks:
        #     # The name of the required check.
        #   - context: ci/build
        #     # The ID of the GitHub App that must provide this check. Omit this field to automatically select the GitHub App that has recently provided this check, or any app if it was not set by a GitHub App. Pass -1 to explicitly allow any app to set the status.
        #     app_id: -1

