---
_extends: .github:common-settings.yaml

repository:
  name: ha-addon-repository
  description: Template repository for a Home Assistant add-on repository
  topics: homeassistant, home-assistant, hassio, addon, addons, template
  is_template: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ['Initialize builds', 'Lint add-on', 'Prettier', 'Renovate / Renovate']
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
