name: Sync Settings

on:
  push:
    branches: [main]
    paths:
      - '.github/settings.yml'
      - '.github/workflows/sync-settings.yaml'
  schedule:
    - cron: '15 14 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  sync-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
          permissions: 'administration:write, contents:read, issues:write, members:write'

      - name: Sync Settings to GitHub
        uses: exivity/actions/sync-defaults@2657caa2439c8dc2e5de368cf46e477c694e5edc # main
        with:
          gh-token: ${{ steps.get_workflow_token.outputs.token }}
